service: papertesla-api

org: arroyodev
app: papertesla-api

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  stackName: ${self:custom.stack}
  tags:
    PROJECT: papertesla
  environment:
    DB_PRICING: ${self:service}-pricing-${opt:stage, self:provider.stage}
    DB_ORDERS: ${self:service}-orders-${opt:stage, self:provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  stack: papertesla-api-${self:custom.stage}
  tableThroughput: 1
  customDomain:
    domainName: api.papertesla.com
    basePath: v1
    stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: false
    zip: true
    usePoetry: false

functions:
  create:
    handler: handler.handler
    role: "ApiHandler"
    events:
      - http:
          path: order
          method: post
          cors: true

resources:
  # Databases
  - ${file(resources/dynamodb/pricing.yml)}
  - ${file(resources/dynamodb/orders.yml)}
  # Roles
  - ${file(resources/roles.yml)}
