Resources:
  OrdersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: ${self:provider.environment.DB_ORDERS}

Outputs:
  OrdersTableArn:
    Value: { Fn::GetAtt: [OrdersTable, Arn] }
