Resources:
  ProductsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      TableName: ${self:provider.environment.DB_PRODUCTS}

Outputs:
  ProductsTableArn:
    Value: { Fn::GetAtt: [ProductsTable, Arn] }
