name: PaperTesla

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12"

      - name: Install Dependencies
        run: npm install

      - name: Serverless Deploy
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
